"""empty message

Revision ID: 158dca97c41b
Revises: 1bc3fc6ba5d3
Create Date: 2023-07-11 15:01:04.142767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158dca97c41b'
down_revision = '1bc3fc6ba5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
