"""Add category field to Task model

Revision ID: 1bc3fc6ba5d3
Revises: e852383898b2
Create Date: 2023-07-11 12:31:30.211531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc3fc6ba5d3'
down_revision = 'e852383898b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
